name: test
on:
  workflow_dispatch:
  push:
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.3.0

      - name: Run unit tests
        run: python3 -m unittest
